package main

import (
	"apigo/algorithm"
	_ "apigo/docs" // docs is generated by Swag CLI, you have to import it.
	"apigo/handlers"
	"log"
	"net/http"

	"github.com/gorilla/mux"
	"github.com/rs/cors"
	httpSwagger "github.com/swaggo/http-swagger"
)

func requestHandler() {
	router := mux.NewRouter().StrictSlash(true)

	// Users Endpoint
	router.HandleFunc("/api/users", handlers.GetUsers).Methods("GET")
	router.HandleFunc("/api/users/{id}", handlers.GetUser).Methods("GET")
	router.HandleFunc("/api/users/register", handlers.CreateUser).Methods("POST")
	router.HandleFunc("/api/users/login", handlers.Login).Methods("POST")

	// Consultations Endpoint
	router.HandleFunc("/api/consultations", handlers.GetAllConsultations).Methods("GET")
	router.HandleFunc("/api/users/{id}/consultations", handlers.GetAllConsultationsByUserId).Methods("GET")
	router.HandleFunc("/api/users/{id}/consultations", handlers.CreateConsultation).Methods("POST")
	// Swagger
	router.PathPrefix("/api/swagger").Handler(httpSwagger.WrapHandler)

	// cors
	c := cors.New(cors.Options{
		AllowedOrigins:   []string{"*"},
		AllowCredentials: true,
	})
	handler := c.Handler(router)
	log.Fatal(http.ListenAndServe(":8080", handler))
}

// @title Gang API
// @version 1.0
// @description This is an API lol
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email soberkoder@swagger.io
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:8080
// @BasePath /api
func main() {
	algorithm.RunRandomForestTraining()
	requestHandler()
}
